languageCode = "en"
languageName = "English"
weight = 1
title = "ShangLyu"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
logo = "img/logo2.png"
secondaryLogo = "img/logo.png"
dateFormat = "2 January 2006"

[author]
name = "Shang"
image = "62023200.png"
bio = "Pentester ğŸ‘¨â€ğŸ’»| Bug Hunter ğŸ| RedTeam ğŸ¥·"
headline = "Pentester ğŸ‘¨â€ğŸ’»| Bug Hunter ğŸ| RedTeam ğŸ¥·"
links = [ { github = "https://github.com/shanglyu" }, { linkedin = "https://www.linkedin.com/in/shanglyu" } ]
